# Generated by Django 4.1.13 on 2024-05-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='speciatlyId',
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciatly',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
