# Generated by Django 4.1.13 on 2024-05-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('umber', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], max_length=10)),
                ('patientId', models.IntegerField(null=True)),
            ],
        ),
    ]
