# Generated by Django 4.1.13 on 2024-05-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSupplies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
