# Generated by Django 4.1.13 on 2024-05-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalsupplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalsupplies',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
