# Generated by Django 4.1.13 on 2024-05-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='patientId',
        ),
    ]
