# Generated by Django 4.1.13 on 2024-05-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='recordId',
            field=models.IntegerField(null=True),
        ),
    ]
